baseURL: 'https://wiki.18xx.site/'
title: '18xx на русском'
theme: 'book'

defaultContentLanguage: 'ru'
languageCode: 'ru-ru'

enableGitInfo: true
disqusShortname: '18xx-ru'

params:
  BookTheme: 'auto'
  BookRepo: 'https://github.com/18xx-ru/18xx-ru.github.io'
  BookComments: true
