baseURL: 'https://18xx-ru.github.io/'
title: '18xx на русском'
theme: 'book'

defaultContentLanguage: 'ru'
languageCode: 'ru-ru'

BookRepo: https://github.com/18xx-ru/18xx-ru.github.io

enableGitInfo: true
